version: '3'
services:
  postgres_database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ufanet
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data